### ISSUE TITLE
Implement a new system for running transformers on explanations

### ISSUE THREAD

**Issue by zyteka** [sibyl-dev/pyreal#150]
## Problem
The current system of Transformers in Pyreal is leading to confusion, with every domain requiring slightly different treatment of explanation transforms. There are 3 situations to consider:

1. The explanation-ready feature is not interpretable: `e_transformers: data_transform, inverse_transform_explanation` 
2. The explanation-ready feature is interpretable: `e_transformers: data_transform`. `i_transformers: data_transform`
3. The feature is not used by the explanation algorithm, but is interpretable: `i_transformers: data_transform, transform_explanation`

Explanation transforms have three possibilities: they can be functional (they change the explanation), they can be no-ops (they don't change the explanation), or they can be process-ending (they don't change the explanation, and require the transformation process to end).

Right now, juggling the feature spaces for both explanations and transformers is confusing. Breaks are very heard to debug. The follow proposal should solve some of these problems. 

## Proposed Solution
Each of these items will be tracked in separate sub-issues

- [x] #154 Shift the burden of tracking what kind of transformer something is from the Explainer to the Transformers themselves. Transformers will maintain three flags that determine when the get called, and Explainers will just have one list of Transformers.
- [x] #158 Add a `return_original_explanation` flag to Explainers. This flag defaults to False. If True, return the explanation right after generating, without any kind of explanation transform. 
- [x] #156 Set explanation transforms to be no-ops by default (don't change the explanation). Generally, attempt to run all `transform_explanation` functions, and if one doesn't work, stop the process and warn. Whenever a default explanation transform function is encountered, print a helpful message explaining that no explanation transform is happening and that this transformer should be get to interpret (or removed from interpret). Additionally, add a custom error called `BreakingTransform`. Users can set Transformers to call this in `transform_explanation` functions. If such an error is encountered, the transformation process stops.
- [x] #161 When generating a local explanation using `.produce(x)`, also generate and return the corresponding `x` in the same feature space as the explanation
- [x] #151 Display clear information about which transform broke if something goes wrong

**Comment by zyteka** [comment]
Completed with the 5 issues described in the issue description.
